// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMARE1EnfpaYz4osN4c4kicqSEtt6WZgA',
    appId: '1:535199382894:web:968e90799d93c2d8f5557f',
    messagingSenderId: '535199382894',
    projectId: 'tiktok-f7ee4',
    authDomain: 'tiktok-f7ee4.firebaseapp.com',
    storageBucket: 'tiktok-f7ee4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5INpP7b7cQit1RE1AO7DiqRWifrZi_Z4',
    appId: '1:535199382894:android:9f63fab1fc5334c3f5557f',
    messagingSenderId: '535199382894',
    projectId: 'tiktok-f7ee4',
    storageBucket: 'tiktok-f7ee4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwKxG33U4nxF7939asseYanSEWvrvnqk',
    appId: '1:535199382894:ios:a3156291c7f90791f5557f',
    messagingSenderId: '535199382894',
    projectId: 'tiktok-f7ee4',
    storageBucket: 'tiktok-f7ee4.firebasestorage.app',
    iosBundleId: 'com.example.tiktokTutorial',
  );
}
